DROP DATABASE IF EXISTS SEARCH;

CREATE DATABASE SEARCH;

USE SEARCH;

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS LOCALRESULTS;
DROP TABLE IF EXISTS URLUSERCOUNTER;
DROP TABLE IF EXISTS KEYWORDSLIST;
DROP TABLE IF EXISTS KEYWORDSCOUNTER;

CREATE TABLE USERS( 
ID INT PRIMARY KEY AUTO_INCREMENT,
ROLE INT,
FIRSTNAME VARCHAR(150) NOT NULL,
LASTNAME VARCHAR(150) NOT NULL,
EMAIL VARCHAR(150) NOT NULL,
PASS VARCHAR(150) NOT NULL,
CONTACT VARCHAR(150) NOT NULL,
ADDRESS VARCHAR(750) NOT NULL,
CITY VARCHAR(150) NOT NULL,
ZIP INT
);

CREATE TABLE LOCALRESULTS(
ID INT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(2083),
METAKEYS VARCHAR(2083),
URL VARCHAR(2083),
DESCRIPTION VARCHAR(2083),
SERVICE VARCHAR(100)
);

CREATE TABLE URLUSERCOUNTER(
ID INT PRIMARY KEY AUTO_INCREMENT,
USERID INT REFERENCES USERS(ID),
URLID INT REFERENCES LOCALRESULTS(ID),
COUNTER INT
);

CREATE TABLE KEYWORDSLIST(
ID INT PRIMARY KEY AUTO_INCREMENT,
KEYWORDS VARCHAR(2083)
);

CREATE TABLE KEYWORDSCOUNTER(
ID INT PRIMARY KEY AUTO_INCREMENT,
KEYID INT REFERENCES KEYWORDLIST(ID),
USERID INT REFERENCES USERS(ID),
COUNTER INT
);

INSERT INTO USERS(ROLE, FIRSTNAME, LASTNAME, EMAIL, PASS, CONTACT, ADDRESS, CITY, ZIP) 
VALUES(1, 'Administrator', 'LASTNAME', 'admin@localhost.com', 'admin', '6264648186', '21, Professor Colony, Devendra Nagar', 'Amravati', 444606);

INSERT INTO USERS(ROLE, FIRSTNAME, LASTNAME, EMAIL, PASS, CONTACT, ADDRESS, CITY, ZIP) 
VALUES(2, 'Pooja', 'Vilayatkar', 'pooja@localhost.com', 'pooja', '8390302721', 'Dokya war', 'Amravati', 444606);

INSERT INTO USERS(ROLE, FIRSTNAME, LASTNAME, EMAIL, PASS, CONTACT, ADDRESS, CITY, ZIP) 
VALUES(2, 'Chittaksh', 'Khadse', 'chitta@localhost.com', 'chitta', '9503555206', 'Jamini war', 'Amravati', 444606);